// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function CreateChat(arg1:string):Promise<number>;

export function DeleteChat(arg1:number):Promise<void>;

export function GetChats():Promise<Array<database.Chat>>;

export function GetMessages(arg1:number):Promise<Array<database.Message>>;

export function RegenerateResponse(arg1:number,arg2:string):Promise<string>;

export function SendMessageToAI(arg1:number,arg2:string):Promise<string>;

export function SetApiKey(arg1:string):Promise<boolean>;

export function UpdateChatTitle(arg1:number,arg2:string):Promise<void>;
