// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1) {
  return window['go']['bindings']['App']['AddBookmark'](arg1);
}

export function CancelGeneration() {
  return window['go']['bindings']['App']['CancelGeneration']();
}

export function CheckForUpdates() {
  return window['go']['bindings']['App']['CheckForUpdates']();
}

export function CreateChat(arg1) {
  return window['go']['bindings']['App']['CreateChat'](arg1);
}

export function DeleteBookmark(arg1) {
  return window['go']['bindings']['App']['DeleteBookmark'](arg1);
}

export function DeleteChat(arg1) {
  return window['go']['bindings']['App']['DeleteChat'](arg1);
}

export function GetBookmarks() {
  return window['go']['bindings']['App']['GetBookmarks']();
}

export function GetChats() {
  return window['go']['bindings']['App']['GetChats']();
}

export function GetMessages(arg1) {
  return window['go']['bindings']['App']['GetMessages'](arg1);
}

export function GetModels() {
  return window['go']['bindings']['App']['GetModels']();
}

export function QuitApp() {
  return window['go']['bindings']['App']['QuitApp']();
}

export function RegenerateResponse(arg1, arg2, arg3) {
  return window['go']['bindings']['App']['RegenerateResponse'](arg1, arg2, arg3);
}

export function SearchChat(arg1) {
  return window['go']['bindings']['App']['SearchChat'](arg1);
}

export function SendMessageToAI(arg1, arg2, arg3) {
  return window['go']['bindings']['App']['SendMessageToAI'](arg1, arg2, arg3);
}

export function SetApiKey(arg1) {
  return window['go']['bindings']['App']['SetApiKey'](arg1);
}

export function SetCloseBehavior(arg1) {
  return window['go']['bindings']['App']['SetCloseBehavior'](arg1);
}

export function ShowWindow() {
  return window['go']['bindings']['App']['ShowWindow']();
}

export function UpdateChatConfiguration(arg1, arg2) {
  return window['go']['bindings']['App']['UpdateChatConfiguration'](arg1, arg2);
}

export function UpdateChatModel(arg1, arg2) {
  return window['go']['bindings']['App']['UpdateChatModel'](arg1, arg2);
}

export function UpdateChatTitle(arg1, arg2) {
  return window['go']['bindings']['App']['UpdateChatTitle'](arg1, arg2);
}

export function UpdateSystemPrompt(arg1, arg2) {
  return window['go']['bindings']['App']['UpdateSystemPrompt'](arg1, arg2);
}
