// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function CancelGeneration():Promise<void>;

export function CheckForUpdates():Promise<void>;

export function CreateChat(arg1:string):Promise<number>;

export function DeleteChat(arg1:number):Promise<void>;

export function GetChats():Promise<Array<database.Chat>>;

export function GetMessages(arg1:number):Promise<Array<database.Message>>;

export function GetModels():Promise<Array<string>>;

export function QuitApp():Promise<void>;

export function RegenerateResponse(arg1:number,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SendMessageToAI(arg1:number,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SetApiKey(arg1:string):Promise<boolean>;

export function SetCloseBehavior(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function UpdateChatConfiguration(arg1:number,arg2:database.ChatConfig):Promise<void>;

export function UpdateChatModel(arg1:number,arg2:string):Promise<void>;

export function UpdateChatTitle(arg1:number,arg2:string):Promise<void>;

export function UpdateSystemPrompt(arg1:number,arg2:string):Promise<void>;
