// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChat(arg1) {
  return window['go']['bindings']['App']['CreateChat'](arg1);
}

export function DeleteChat(arg1) {
  return window['go']['bindings']['App']['DeleteChat'](arg1);
}

export function DeleteLastResponse(arg1) {
  return window['go']['bindings']['App']['DeleteLastResponse'](arg1);
}

export function GetChats() {
  return window['go']['bindings']['App']['GetChats']();
}

export function GetMessages(arg1) {
  return window['go']['bindings']['App']['GetMessages'](arg1);
}

export function SendMessageToAI(arg1, arg2) {
  return window['go']['bindings']['App']['SendMessageToAI'](arg1, arg2);
}

export function SetApiKey(arg1) {
  return window['go']['bindings']['App']['SetApiKey'](arg1);
}

export function UpdateChatTitle(arg1, arg2) {
  return window['go']['bindings']['App']['UpdateChatTitle'](arg1, arg2);
}
